# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-24 15:38
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminIMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=200, null=True, verbose_name='文件名')),
                ('img', models.ImageField(upload_to='./admin')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='文章')),
                ('photo', models.ImageField(height_field='url_height', upload_to='avatar', verbose_name='插图', width_field='url_width')),
                ('Cname', models.CharField(blank=True, max_length=50, null=True, verbose_name='作者名')),
                ('Createtime', models.DateField(auto_now_add=True, null=True, verbose_name='创作时间')),
                ('updatedtime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('text', DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='正文')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'Article',
                'ordering': ['-updatedtime'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('body', models.TextField(blank=True, null=True, verbose_name='评论正文')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='作品')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标签名')),
                ('updatetime', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('createtime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '作品标签',
                'verbose_name_plural': '作品标签',
                'db_table': 'Label',
                'ordering': ['-updatetime'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='label',
            field=models.ManyToManyField(to='blog.Label', verbose_name='标签'),
        ),
    ]
